### ISSUE TITLE
Add "About page"

### ISSUE THREAD

**Issue by pzwsk** [okgreece/thess_geonode#12]
The Risk Data Portal of Thessaloniki is an online geospatial data catalog where registered data owners can share geospatial data, metadata and related documents as open data or to a limited group of registered users, and where any user can preview and download geospatial data, metadata and related documents.

The Risk Data Portal is intended to help the community of risk stakeholders to improve the Resilience of the city of Thessaloniki.

The Risk Data Portal is a project initiated by the Resilient Initiative of Thessaloniki in collaboration with the World Bank. The website is jointly managed by the GIS and the eGov departments of the municipality.

The Risk Data Portal, based on the open source GeoNode software has been deployed with technical support from Open Knowledge Greece and EOFarm.

**Comment by pzwsk** [comment]
In the meantime, remove  "Supported by Open Knowledge Greece & EOfarm"  in the footer.

**Comment by echondrok** [comment]
Done. http://riskdata.thessaloniki.gr/portal_about
